# Test workflow
name: Tests
on: push
jobs:
    test_job:
        name: Test Job
        runs-on: ubuntu-latest
        steps:
            - name: Setup workspace
              uses: dynod/repo-checkout@v1
              with:
                  url: https://github.com/dynod/workspace.git
                  group: tools
            - name: Run tests
              uses: dynod/call-make@v1
              with:
                  path: tools/pytest-multilog
                  target: tests
            - name: Archive Python distribution
              uses: actions/upload-artifact@v1
              with:
                  name: dist
                  path: tools/pytest-multilog/out/artifacts/python
            - name: Archive flake8 report
              uses: actions/upload-artifact@v1
              with:
                  name: flake8 report
                  path: tools/pytest-multilog/out/flake-report
            - name: Archive coverage report
              uses: actions/upload-artifact@v1
              with:
                  name: coverage report
                  path: tools/pytest-multilog/out/coverage-report
            - name: Archive tests report
              uses: actions/upload-artifact@v1
              with:
                  name: tests logs and report
                  path: tools/pytest-multilog/out/tests
